# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build mac amd64
        run: GOOS=darwin GOARCH=amd64 go build -o wechat-sticker-downloader-amd64 ./...
      - name: Build mac 386
        run: GOOS=darwin GOARCH=386 go build -o wechat-sticker-downloader-386 ./...
      - name: Build mac arm64
        run: GOOS=darwin GOARCH=arm64 go build -o wechat-sticker-downloader-arm64 ./...

      - name: Test
        run: go test -v ./...
