# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build mac amd64
        run: GOOS=darwin GOARCH=amd64 go build -o wechat-sticker-downloader-amd64 ./...
      - name: Build mac arm64
        run: GOOS=darwin GOARCH=arm64 go build -o wechat-sticker-downloader-arm64 ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wechat-sticker-downloader-amd64
            wechat-sticker-downloader-arm64
